export const LOGIN='LOGIN'
export const GET_STORE_IMAGE='GET_STORE_IMAGE'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGOUT='LOGOUT'
export const SET_STORE_IMAGE='SET_STORE_IMAGE';
export const ADD_MORE_IMAGE='ADD_MORE_IMAGE'